import { Geist, Geist_Mono ,DM_Sans,  Indie_Flower, } from "next/font/google";
import "./globals.css";
import Header from "@/common-component/Header/Header";
import Footer from "@/common-component/Footer/Footer";
import ProgressBar from "@/common-component/ProgressBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700"],
});
export const indieFlower = Indie_Flower({
  subsets: ["latin"],
  variable: "--font-indie-flower",
   weight: ["400"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${indieFlower.variable} ${dmSans.variable} antialiased`}
      >
        <ProgressBar />
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
